# handler.py
import os
import base64
import time
import requests
import runpod
from supabase import create_client

# استدعاء المكتبات الرسمية
from together import Together

# الاستيراد الدقيق والنظامي بناءً على ملفاتك ودوالك في مستودع GitHub
from translator_helper import get_epic_prompt
from styles_config import STYLE_ENHANCERS, AVATAR_NEGATIVE_PROMPT
from dimensions_config import get_image_dimensions  # دالتك الاحترافية للمقاسات

# جلب إعدادات البيئة من RunPod
TOGETHER_API_KEY = os.getenv("TOGETHER_API_KEY", "").strip()
HF_TOKEN = os.getenv("HF_TOKEN", "").strip()  # مفتاح الـ Hugging Face الجديد الخاص بك
SUPABASE_URL = os.getenv("SUPABASE_URL", "").strip().rstrip('/')
SUPABASE_KEY = os.getenv("SUPABASE_KEY", "").strip()
BUCKET_NAME = "MyFirstImagesTest1"

def handler(job):
    try:
        print("--- [START] SMARTGEN HYBRID MULTI-ENGINE ---")
        job_input = job.get('input', {})
        
        # استلام المدخلات الأساسية من الموقع
        raw_prompt = job_input.get('prompt')
        style_key = job_input.get('style', 'photorealistic')

        if not raw_prompt:
            print("--- [ERROR] Input prompt is missing ---")
            return {"error": "Prompt is missing."}

        # 1. استدعاء المترجم والمحسن الذكي (GPT-4o)
        print("--- [STEP 1] Activating OpenAI Prompt Engineer (GPT-4o)... ---")
        optimized_prompt = get_epic_prompt(raw_prompt)

        # 2. استدعاء النمط المناسب من ملف الأنماط الخاص بك
        style_details = STYLE_ENHANCERS.get(style_key, STYLE_ENHANCERS["photorealistic"])
        final_positive_prompt = f"{optimized_prompt}, {style_details}"

        # 3. استدعاء الأبعاد والمقاسات الديناميكية
        width, height = get_image_dimensions(job_input)
        print(f"--- [STEP 2] Style: {style_key} | Resolution: {width}x{height} ---")

        # متغير لحفظ البايتات النهائية للصورة لتمريرها لـ Supabase
        image_bytes = None
        engine_used = ""

        # 4. شرط التوجيه الذكي (شرطي المرور) بناءً على الستايل المختار
        if style_key == "cartoon":
            print("--- [STEP 3] Routing to Hugging Face (Animagine XL 2D Engine)... ---")
            engine_used = "Animagine XL (Hugging Face)"
            
            # رابط الـ API المجاني لموديل الأنمي والكرتون ثنائي الأبعاد البحت
            HF_API_URL = "https://api-inference.huggingface.co/models/cagliostrolab/animagine-xl-3.1"
            
            # إرسال الطلب لـ Hugging Face
            response = requests.post(
                HF_API_URL,
                headers={"Authorization": f"Bearer {HF_TOKEN}"},
                json={
                    "inputs": final_positive_prompt,
                    "parameters": {
                        "width": width,
                        "height": height,
                        "num_inference_steps": 28  # يعطي تفاصيل ممتازة للرسم المسطح
                    }
                }
            )
            
            if response.status_code != 200:
                print(f"--- [FAILED] Hugging Face Error: {response.text} ---")
                return {"error": f"Hugging Face API Error: {response.text}"}
                
            # هقينج فيس يعيد بكسلات الصورة مباشرة (Binary Content)
            image_bytes = response.content

        else:
            print("--- [STEP 3] Routing to Together AI (FLUX Engine)... ---")
            engine_used = "FLUX.1 [schnell] (Together AI)"
            
            client = Together()
            response = client.images.generate(
                model="black-forest-labs/FLUX.1-schnell",
                prompt=final_positive_prompt,
                width=width,
                height=height,
                steps=4,
                response_format="b64_json"
            )
            
            # استخراج البكسلات وفك تشفيرها من Together AI
            b64_data = response.data[0].b64_json
            image_bytes = base64.b64decode(b64_data)

        # 5. الرفع المشترك والمستقر إلى باكت Supabase
        print(f"--- [STEP 4] Uploading Output to Supabase bucket: {BUCKET_NAME} ---")
        sb_client = create_client(SUPABASE_URL, SUPABASE_KEY)
        
        # تسمية الملف بناءً على المحرك المستخدم لمنع التداخل
        file_name = f"smartgen_{style_key}_{int(time.time())}.png"
        
        storage = sb_client.storage.from_(BUCKET_NAME)
        storage.upload(path=file_name, file=image_bytes, file_options={"content-type": "image/png"})
        
        # جلب الرابط المباشر العام للصورة
        public_url = storage.get_public_url(file_name)
        print(f"--- [SUCCESS] Image generated by {engine_used} is live! ---")
        
        return {
            "image_url": public_url,
            "status": "success",
            "metadata": {
                "style_used": style_key,
                "dimensions": f"{width}x{height}",
                "engine": engine_used
            }
        }

    except Exception as e:
        print(f"--- [FATAL ERROR] ---: {str(e)}")
        return {"error": str(e)}

# تشغيل السيرفر المستمر على RunPod والاستماع للموقع
runpod.serverless.start({"handler": handler})
